### ISSUE TITLE
Tasks not showing on the browser

### ISSUE THREAD

**Issue by yarcx** [john-smilga/node-express-course#11]
So after doing all the server-side codes and connecting it to the public file so I could see the list of my tasks on the browser, i noticed I was getting an error. 
After debugging turns out the error was coming from here, "line number 11"
![image](https://user-images.githubusercontent.com/55262580/140725462-6a2b09a2-faf9-4d5b-b50a-bd9a40216843.png)

So the issue was we were trying to destructure tasks from the returned data, instead of renaming data to tasks,

`const {data: {tasks}} = axios.get('api/v1/tasks')` this is throws an error 

`const {data: tasks} = axios.get('api/v1/tasks')` this works fine

**Comment by john-smilga** [comment]
Yes, it all depends on structure of the response in my case it was
res.json({tasks}) in your case it sounds like you have res.json(tasks)
