### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by mayankdutta** [john-smilga/node-express-course#18]
https://github.com/john-smilga/node-express-course/blob/d45f10d5271f7236f3337332e99de6ce53e81a8e/03-task-manager/starter/public/browser-app.js#L11

This should be
```js
 const {
            data: tasks,
        } = await axios.get('/api/v1/tasks')

```

**Comment by john-smilga** [comment]
Well, depends on your server setup. If you follow the video, then everything is going to work as it is.
