### ISSUE TITLE
.status(200) doesn't work as the status code in DevTools is 304

### ISSUE THREAD

**Issue by peskee** [john-smilga/node-express-course#23]
In 03-express-basics.js we should set up our custom status which is 200 as shown, but inside DevTools status becomes 304 after site refreshes
![1](https://user-images.githubusercontent.com/103512458/180613138-9260aff1-3289-4137-98ca-deccb4ea5749.PNG)
s

**Comment by Abdul-wahab-shahzad** [comment]
This is a bug in chrome . Try using a different web browser. 

https://bugs.chromium.org/p/chromium/issues/detail?id=1269602 

the link to the bug in chrome.
